version: '3'
 
services:
  sqlcontainer:
    image: mysql:5.7
    restart: always
    env_file: ./app/.env
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
      MYSQL_USER: root_user
      MYSQL_PASSWORD: abc123
    ports:
      - 6033:3306
    volumes: 
      - db-config2:/etc/mysql
      - db-data2:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: timdanderson1/myfirstdeployment:1.0
    env_file: ./app/.env
    ports:
      - 3000:3000
    depends_on:
      - sqlcontainer
    stdin_open: true
    tty: true

volumes: 
  db-config2:
  db-data2: