version: '3'
 
services:
  sqlcontainer:
    image: mysql:5.7
    restart: always
    env_file: ./app/.env
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes: 
      - db-config2:/etc/mysql
      - db-data2:/var/lib/mysql
      - ./db/backup/files/:/data_backup/data

  app:
    build:
      context: .
      dockerfile: ./app/Dockerfile
    image: node-mysql-app-demo3
    env_file: ./app/.env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    depends_on:
      - sqlcontainer
    stdin_open: true
    tty: true

volumes: 
  db-config2:
  db-data2: